### PR TITLE
Replace hardcoded yay with user-config aur wrapper for single install

### PR DESCRIPTION
**Pull request by Schlaefer**
I only took a quick glance at the code, but it seems this was missed when switching from yay to a generic wrapper?

### CODE REVIEW

**Comment by dhruv8sh** [comment]
This calls for a cleanup to the PackageManager.qml file.
Thanks for pointing it out, great job!

**Comment by dhruv8sh** [comment]
It was cleaned up. If you have the time, please review it.

**Comment by Schlaefer** [comment]
> It was cleaned up. If you have the time, please review it.

OK, I'm far from a QML guru, so the framing is "I know some of these words" and let's try if I can understand it. Just skimming over the code of PackageManager.qml, but since you asked here are my 5 cents. :)

Much better than before, a lot more concise.

The *-e hold* is floating around to loosely. Sometimes it's *term+hold*, sometimes it's *term + " --hold -e". This makes the code hard to evaluate. There should be be one central instance that manages the *--hold* and independent from the *-e*. Consolidate it in the *executable.exec()* call?

**Comment by dhruv8sh** [comment]
Agreed! Will make the changes.

**Pull request merged**
